### ISSUE TITLE
Feladat beadás nem látod a képet amit bekültél

### ISSUE THREAD

**Issue by Darknet500** [Abokyy/A802app#10]
Amikor egy kitűzőhöz képet csatolsz akkor ott csak egy zöld téglalapot mutat a kép helyett:
![Screenshot_20200328_150002_csapat app](https://user-images.githubusercontent.com/62722597/77824747-3ec38e80-7105-11ea-9e25-0db932708490.jpg)
Viszont amikor a beadott feladataidat nézed akkor már látod a képet amit beadtál :)

**Comment by Abokyy** [comment]
[Solved] Az alap képet át akartam színezni, ezért tettem rá a zöld festék módot. Levettem így már látszik a hozzáadott kép.
