### ISSUE TITLE
Elcrashelt az app

### ISSUE THREAD

**Issue by BigT111** [Abokyy/A802app#7]
Tehát letöltöttem az új apk-t és bejelentkeztem. Jól működött és a szemétszedős badge is jó lett!
Megnyitottam a csapatfelépítést, rámentem az Ánizsillatú pókhálósgomba rajra majd rákattintottam a Chili őrsre. Először a szokásos fekete képet adta be és visszadobott a kezdőlapra. Ha ezt a műveletet megismételtem akkor meg kiírta hogy a 802 app folyamatosan leáll. Ezekről csatolok képet.

![Screenshot_20200327-091647_802-es app](https://user-images.githubusercontent.com/62723607/77736231-4b17f080-700c-11ea-814a-69569b08ca8d.jpg)

![Screenshot_20200327-091136_802-es app](https://user-images.githubusercontent.com/62723607/77736254-4f440e00-700c-11ea-8e98-f9a55af2b6fc.jpg)

(((Lehet(nemtudom) ez azért van mert még az őrsök nincsenek adatokkal feltöltve, ezt nemtudom de leírtam a tapasztalatomat.)))

**Comment by Abokyy** [comment]
[Solved] Az adatbázisban nem volt fent a Chili őrs, ezért nem tudott mit megjeleníteni az őrsi részletek nézet.
